peopleService.URL: http://localhost:8082/v1/people
personService.URL: http://localhost:8082/v1/people/%s
accountsService.URL: http://localhost:8081/v1/people/%s/accounts
billsService.URL: http://localhost:8081/v1/bills
billsByAccountIdService.URL: http://localhost:8081/v1/account/%s/bills

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true

thymeleaf:
  prefix: classpath:/templates/
